Repository CokeLee777/spring-security-jwt-auth, pull requests merged in 2023-06, with the labels that each got.

#28 [BUG] 인증된 사용자 로그인, 회원가입 요청 처리
  src/main/java/io/github/cokelee777/springsecurityjwtauth/exception/DuplicatedAuthenticationException.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/config/JwtSecurityConfiguration.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtAuthenticationFilter.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/filter/JwtMemoryAuthorizationFilter.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/handler/failure/JwtAuthenticationFailureHandler.java
Labels: bug, enhancement

#29 [FEATURE] Jwt 로그아웃 로직 작성
  src/main/java/io/github/cokelee777/springsecurityjwtauth/exception/UserNotFoundException.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/config/JwtSecurityConfiguration.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/handler/logout/JwtLogoutHandler.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/handler/logout/JwtLogoutSuccessHandler.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/handler/success/JwtMemoryAuthenticationSuccessHandler.java
Labels: enhancement

#35 [FEATURE] Lombok and Annotation filter
  build.gradle
  src/main/java/io/github/cokelee777/springsecurityjwtauth/SpringSecurityJwtAuthApplication.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/annotations/DataBase.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/annotations/Memory.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/config/PasswordEncoderConfiguration.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/controller/UserController.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/dto/GetProfileResponseDto.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/dto/SignUpResponseDto.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/entity/DBUser.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/entity/MemoryUser.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/exception/DuplicatedUserException.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/repository/DBUserRepository.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/repository/MemoryUserRepository.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/repository/UserRepository.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/auth/JwtUserDetails.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/config/JwtSecurityConfiguration.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/handler/success/JwtAuthenticationSuccessHandler.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/provider/JwtAuthenticationProvider.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/service/JwtUserDetailsService.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/token/extractor/JwtTokenExtractor.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/token/provider/JwtTokenProvider.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/security/token/service/JwtTokenService.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/service/DBUserService.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/service/MemoryUserService.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/service/UserService.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/service/UserServiceImpl.java
  src/main/java/io/github/cokelee777/springsecurityjwtauth/utils/PasswordUtils.java
Labels: documentation, enhancement, refactor

#37 [DOCS] JPA 도입에 따른 README 수정
  README.md
  asset/images/authentication_flow_diagram.png
  asset/images/authorization_flow_diagram.png
  asset/images/signout_flow_diagram.png
Labels: documentation
